
$(function(){allJs();if($('#heardout:first').isExist()){xueYuanHead();}
if($('.courseList:first').isExist()){courselistPage();return;}
if($('#hbanner:first').isExist()){homePage();return;}
if($('.xyHome:first').isExist()){changeImg();xyHomePage();return;}
if($('.courseDetail:first').isExist()){courseDetail();if($('.courseView:first').isExist()){courseView();return;}
return;}});$(document).ready(function(){var erwei_image_url="http://imgcache.qq.com/ac/www_tencent/daxue/img/wachat_erweima.jpg";var erwei_html='<div class="erwei_div"><p>更多腾讯活动资讯</p><img src="'+erwei_image_url+'" width="120" height="120" style="width:120px; height:120px;" /><p>关注腾讯大学公号</p></div><div class="clr"></div>';if($("#learwhat").html()!=null){$("#learwhat").children().children().eq(0).after(erwei_html);}
if($(".gonggao").html()!=null){$(".gonggao").children().eq(1).after(erwei_html);}
if($(".indexBut").html()!=null){$(".indexBut").append(erwei_html);}});function courseView(){videoId=typeof(videoId)=='undefined'?'0':videoId;if(videoId=='0')return;var viewCookieName='ved'+videoId;if(getCookie(viewCookieName)!='1'){setCookie(viewCookieName,'1',3600000);playCountAdd1(videoId);}
var score_avg=$('.score_avg:first');var the_star=0;$('.showbstar:first span').hover(function(){the_star=$(this).attr('star');$(this).parent().attr('class','outbstar'+the_star+' showbstar');score_avg.text(parseInt(the_star)*2);},function(){$(this).parent().attr('class','outbstar'+$(this).parent().attr('def')+' showbstar');score_avg.text(score_avg.attr('avg'));}).click(function(){var viewCookieName='ced'+videoId;if(getCookie(viewCookieName)=='1'){score_avg.text('已评');}else{setCookie(viewCookieName,'1',3600000*24);score_avg.text('提交中');scoreForCourse(videoId,$(this).attr('star'));}});}
function examine(){var examineShow=$('#examineShow');var viewCookieName='dced';if(getCookie(viewCookieName)=='1'){examineShow.text('您已经参与过了。');return;}else{setCookie(viewCookieName,'1',3600000*24);}
var manyi=false;$('.manyi').each(function(){if($(this).attr('checked')){manyi=$(this).val();return false;}});if(manyi){examineShow.text('提交中...');$.ajax({url:url_root+'home/examine',data:'manyi='+manyi,type:'POST',dataType:'text',timeout:15000,error:function(){},success:function(text){var r=eval('('+text+')');if(r['flag']){examineShow.text('提交成功，感谢您的反馈！');$("#showRe").css("display","");}else{examineShow.text('提交失败，请稍后再试！');}}});}else{examineShow.text('请先选择满意度');}}
function showResult(){$("#footer").find(".diaocha1").css("display","none");$("#footer").find(".diaocha2").css("display","block");$.ajax({url:url_root+'home/getInvesNum',data:'',type:'POST',dataType:'text',timeout:15000,error:function(){},success:function(text){var r=eval('('+text+')');if(r){var max=0;for(var i=0;i<r.length;i++){$(".diaocha2").find(".invRe"+r[i]['manyi']).next().text(r[i]['NUM']+"票");if(max<parseInt(r[i]['NUM']))max=parseInt(r[i]['NUM']);}
for(var i=0;i<r.length;i++){var temp=162*(parseInt(r[i]['NUM'])/max);if(temp<1){$(".diaocha2 .invRe"+r[i]['manyi']).css("width","1px");}else{$(".diaocha2 .invRe"+r[i]['manyi']).css("width",temp+"px");}}}}});}
function backInves(){$("#footer").find(".diaocha2").css("display","none");$("#footer").find(".diaocha1").css("display","block");}
function scoreForCourse(videoId,star){$.ajax({url:url_root+'course/giveScore',data:'videoId='+videoId+'&star='+star,type:'POST',dataType:'text',timeout:15000,error:function(){},success:function(text){var r=eval('('+text+')');if(r['flag']){$('.score_avg:first').text(r['avg']).attr('avg',r['avg']);}else{}}});}
function playCountAdd1(videoId){$.ajax({url:url_root+'course/playCount',data:'videoId='+videoId,type:'POST',dataType:'text',timeout:15000,error:function(){},success:function(text){}});}
function allJs(){if(typeof(mustShowLogin)!='undefined'&&mustShowLogin){showLogin(true);}
var num=0;var numO=null;$('.n2r').each(function(){num=parseInt($(this).text());if(isNaN(num))return;if(num>9999){numO=new Number(num/10000);$(this).text(numO.toFixed(1)+'万');}});$('[placeholder]').each(function(){$(this).focus(function(){if($(this).val()==$(this).attr('placeholder')){$(this).val('');}
$(this).addClass('searchinp2');}).blur(function(){if($(this).val()==''){$(this).val($(this).attr('placeholder'));}
$(this).removeClass('searchinp2');}).val($(this).val()==''?$(this).attr('placeholder'):$(this).val());});var isIe6=$.browser.msie&&($.browser.version=='6.0');var isHome=$('#hbanner:first').isExist();var returnTop=$('#returnTop');var heardout=$('#heardout');if(isIe6){returnTop.css({'bottom':'auto','position':'absolute'});if(isHome){heardout.css({'bottom':'auto','position':'absolute'});}}
$(window).scroll(function(){if(isIe6&&isHome){heardout.css('top',$(window).scrollTop()+'px');}
if($(window).scrollTop()>200){returnTop.css('display','block');if(isIe6){returnTop.css('top',$(window).scrollTop()+document.documentElement.clientHeight-160+'px');}}else{returnTop.css('display','none');}}).scroll();$('#returnTop .goTop').click(function(){$(window).scrollTop(0);});}
function xyHomePage(){var allimg=$('#xyBanner .items a');var big_img=$('#xyBanner .big');$.ml.butShowTab2(allimg,big_img);stop2=false;$('#xyBanner').mouseover(function(){stop2=true;}).mouseout(function(){stop2=false;});var marquee2=autoSwitchHomeBanner(allimg);MyMar2=setInterval(marquee2,6000);function autoSwitchHomeBanner(allimg){return(function(){if(stop2)return;var next=$('#xyBanner .items .active:first').next();if(next.length==0){next=allimg.eq(0);}
next.mouseover();stop2=false;});}}
function xueYuanHead(){$('.changeModOut:first').hover(function(){$(this).addClass('active');},function(){$(this).removeClass('active');});$('.submenu1').hover(function(){$(this).addClass('active');},function(){$(this).removeClass('active');});}
function courselistPage(){leftandrightTheSameHeight($('.courseleft:first'),$('.courseright:first'));}
function leftandrightTheSameHeight(left,right){var lLen=left.height();var rLen=right.height();if(lLen>rLen){right.css('min-height',(lLen+'px'));}else{left.css('min-height',(rLen+'px'));}
right.add(left).find('img').each(function(){$(this).load(function(){var lLen=left.height();var rLen=right.height();if(lLen>rLen){right.css('min-height',(lLen+'px'));}else{left.css('min-height',(rLen+'px'));}});});}
function homePage(){var allimg=$('#hbanner .items a');var big_img=$('#hbanner .big');var big_a=big_img;stop2=false;$.ml.butShowTab2(allimg,big_img);$('#hbanner').mouseover(function(){stop2=true;}).mouseout(function(){stop2=false;});var marquee2=autoSwitchHomeBanner(allimg);MyMar2=setInterval(marquee2,6000);function autoSwitchHomeBanner(allimg){return(function(){if(stop2)return;var next=$('#hbanner .items .active:first').next();if(next.length==0){next=allimg.eq(0);}
next.mouseover();stop2=false;});}}
function changeImg(){$('#changeImg').each(function(){var changeimg=$(this).find('.bigImg');var dot=$(this).find('.wait_Img');dot.mouseover(function(){if($(this).hasClass('active'))return;var img=$(this).attr('pic');var href=$(this).attr('href');var v=$(this).attr('v');if(changeimg.queue('fx').length!=0){changeimg.stop(true);}
dot.removeClass('active');$(this).addClass('active');if($(this).hasClass('desc')){changeimg.unbind('click');}else{changeimg.click(function(){showHomeVideo(v);});}
changeimg.animate({'opacity':'0.2'},'slow',function(){changeimg.css('background-image','url('+img+')');changeimg.animate({'opacity':'1'},'slow');});});});}
function courseDetail(){$('#content .contbl .c2:first').css('min-height',($('#content .contbr:first').height()+'px'));var buts=['.courseDetail .contbl .but'];var tabs=['.courseDetail .contbl .tab'];var butsE=$('.courseDetail .contbl .but');function backfn1(i){butsE.removeClass('active noborder').eq(i).addClass('active');butsE.eq(i-1).addClass('noborder');$('#content .contbl .c2:first').css('min-height',($('#content .contbr:first').height()+'px'));}
$.ml.butShowTab(buts,tabs,-1,'click',null,backfn1,0);$('.starts a').each(function(){$(this).hover(function(){if($(this).hasClass('start1')){$(this).parent().addClass('starts1');}else if($(this).hasClass('start2')){$(this).parent().addClass('starts2');}else if($(this).hasClass('start3')){$(this).parent().addClass('starts3');}else if($(this).hasClass('start4')){$(this).parent().addClass('starts4');}else if($(this).hasClass('start5')){$(this).parent().addClass('starts5');}},function(){$('.starts').removeClass('starts1 starts2 starts3 starts4 starts5');});});}
function shareto(sign,pos,the){var f=encodeURIComponent('http://daxue.qq.com/');var thet='腾讯大学向您推荐课程，“'+$('#courseTitle').text()+'”';var t=encodeURIComponent(thet);var u=encodeURIComponent(window.location.href);var c=encodeURIComponent(thet+'\n'+u);if(sign=='sinat'){window.open('http://v.t.sina.com.cn/share/share.php?title='+t+'&url='+u);}else if(sign=='qqt'){window.open('http://v.t.qq.com/share/share.php?title='+t+'&url='+u+'&site='+f);}else if(sign=='kaixin001'){window.open('http://www.kaixin001.com/repaste/share.php?rtitle='+t+'&rurl='+u+'&ufrom='+f+'&rcontent='+c);}else if(sign=='renren'){window.open('http://share.renren.com/share/buttonshare.do?title='+t+'&link='+u+'&content=');}else if(sign=='qzone'){window.open('http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?site='+f+'&url='+u+'&title='+t);}else if(sign=='pengyou'){window.open('http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?to=pengyou&site='+f+'&url='+u+'&title='+t);}}
function showLogin(){var url=encodeURIComponent(window.location.href);var src='http://ui.ptlogin2.qq.com/cgi-bin/login?appid=537000001&s_url='+url+'&hide_title_bar=0';var frame='<iframe width="100%" scrolling="no" frameborder="0" src="'+src+'" style="height: 210px;width:400px;" border="0" allowtransparency="true" id="login_frame" name="login_frame"></iframe>';var html=frame;$(html).setLightBox({layoverBg:'#000',layoverOpa:'0.1',alertdivBg:'#fff',alertdivWidth:'490px',closeBut:'.closebut',layerdivClick:true,dragbody:'#loginalert .t'});$('#login_frame').attr('src',src);}
function ptlogin2_onClose(){if(typeof(mustShowLogin)!='undefined'&&mustShowLogin){window.location.href='http://daxue.qq.com';}
$.ml.closeLightBox();}
function ptlogin2_onResize(width,height){var login_frame=document.getElementById("login_frame");if(login_frame){login_frame.style.width=width+"px";login_frame.style.height=height+"px";login_frame.style.visibility="hidden";login_frame.style.visibility="visible";}}
function showHomeVideo(vid){var html='<div id="homevideo1"><div id="homevideo2" onmouseover="$(\'#closebut\').css(\'display\',\'block\');" onmouseout="$(\'#closebut\').css(\'display\',\'none\');">'+getVideoHtml(vid)+'<a id="closebut" herf="javascript:;" style="display:none;"></a></div></div>';jQuery(html).setLightBox({layoverBg:'#000',layoverOpa:'0.5',alertdivBg:'#fff',alertdivWidth:'726',alertdivHeight:'417',sureBut:'#download',closeBut:'#closebut',layerdivClick:true,canNotDrag:false});var video=new tvp.VideoInfo();video.setVid(vid);var player=new tvp.Player(720,411);player.setCurVideo(video);player.addParam("flashskin","http://imgcache.qq.com/minivideo_v1/vd/res/skins/TencentPlayerMiniSkin.swf");player.addParam("loadingswf","http://imgcache.qq.com/minivideo_v1/vd/res/skins/web_small_loading.swf");player.addParam("autoplay",1);player.addParam("wmode",'Opaque');player.write("mod_player");}
function getVideoHtml(vid){return'<div id="mod_player"></div>';var html='<object width="720" height="411" align="middle" id="flashplayer" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codeBase="http://fpdownload.macromedia.com/get/flashplayer/current/swflash.cab#version=10,0,0,0" >'+'<PARAM NAME="FlashVars" VALUE="version=20110407&amp;vid='+vid+'&amp;autoplay=1&amp;list=0&amp;loadingswf=http://imgcache.qq.com/minivideo_v1/vd/res/skins/web_small_loading.swf&amp;skin=http://imgcache.qq.com/minivideo_v1/vd/res/skins/TencentPlayerMiniSkin.swf&amp;">'+'<PARAM NAME="Movie" VALUE="http://static.video.qq.com/TencentPlayer.swf">'+'<PARAM NAME="Src" VALUE="http://static.video.qq.com/TencentPlayer.swf">'+'<PARAM NAME="WMode" VALUE="Opaque">'+'<PARAM NAME="Quality" VALUE="High">'+'<PARAM NAME="AllowScriptAccess" VALUE="always">'+'<PARAM NAME="AllowNetworking" VALUE="all">'+'<PARAM NAME="AllowFullScreen" VALUE="true">'+'<embed width="720" height="411" align="middle" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" bgcolor="#000000" id="flashplayer" name="_playerswf" quality="high" src="http://static.video.qq.com/TencentPlayer.swf" flashvars="version=20110407&amp;vid='+vid+'&amp;autoplay=1&amp;list=2&amp;loadingswf=http://imgcache.qq.com/minivideo_v1/vd/res/skins/web_small_loading.swf&amp;skin=http://imgcache.qq.com/minivideo_v1/vd/res/skins/TencentPlayerMiniSkin.swf&amp;" wmode="Opaque">'+'</object>';return html;}/*  |xGv00|d579bb81b4675c2fcd81b7a35473acaa */