
(function($){$.fn.isExist=function(){if($(this).length==0)return false;else return true;};$.fn.searchRemind=function(options){var left=options.left?options.left:'0';var top=options.top?options.top:'25px';var width=options.width?options.width:'200px';var url=options.url;var index=0;var getstr='';var inputstr='';var activeOutdiv=null;var activeInterviewer=null;var activeTheinput=null;this.each(function(index){$(this).parent().css('position','relative').css('z-index',999);$(this).attr('autocomplete','off');$(this).after('<div class="searchoutdiv" style="z-index:9999;left:'+left+';top:'+top+';width:'+width+';position:absolute;background-color:#fff;border:1px solid #888;display:none;"></div>');$(this).keyup(function(event){var outdiv=$(this).next('.searchoutdiv');if(event.keyCode==13||event.keyCode==27){outdiv.html('').css('display','none');return;}
inputstr=$(this).val();getstr='';if(inputstr==''){outdiv.css('display','none');return;}
if(event.keyCode==38||event.keyCode==40)return;var items=getInterviewerByKey(inputstr,10);var items_len=items.length;if(items_len==0){outdiv.html('');return;}
activeOutdiv=outdiv;activeTheinput=$(this);activeInterviewer=$(this).parent().find('.interviewer');$(this).parent().css('z-index',1000);outdiv.css('display','block');index=0;outdiv.html('');for(var i=0;i<items_len;i++){outdiv.append('<div val="'+items[i][0]+'">'+items[i][1]+'</div>');}
outdiv.find('div').each(function(i){$(this).mouseover(function(){index=i+1;outdiv.find('div').css('background-color','#fff');$(this).css('background-color','#888');}).mouseout(function(){index=0;outdiv.find('div').css('background-color','#fff');$(this).css('background-color','#fff');}).click(function(){activeTheinput.attr('value',$(this).text());activeInterviewer.val($(this).attr('val'));}).css('cursor','default');});});});$('body').click(function(){$('.searchoutdiv').html('').css('display','none').parent().css('z-index',999);});$('body').keydown(function(event){if(!activeOutdiv||activeOutdiv.css('display')=='none')return;if(event.keyCode==38){if(index<=1)index=activeOutdiv.find('div').length+1;index--;activeOutdiv.find('div').css('background-color','#fff');outdiv_item=activeOutdiv.find('div').eq(index-1);outdiv_item.css('background-color','#888');activeTheinput.attr('value',outdiv_item.text());activeInterviewer.val(outdiv_item.attr('val'));}
if(event.keyCode==40){if(index==activeOutdiv.find('div').length)index=0;index++;activeOutdiv.find('div').css('background-color','#fff');outdiv_item=activeOutdiv.find('div').eq(index-1);outdiv_item.css('background-color','#888');activeTheinput.attr('value',outdiv_item.text());activeInterviewer.val(outdiv_item.attr('val'));}
if(event.keyCode==13||event.keyCode==27){$('.searchoutdiv').html('').css('display','none').parent().css('z-index',999);}});};$.ml={butShowTab:function(buts,tabs,num,targe,backfn,startfn,speed){if(num>=0){$(tabs.join()).css('display','none');$(tabs.join()).eq(num).css('display','block');}
$(buts.join()).each(function(i){eval('$(this).'+targe+'(function(){'+'if(!startfn||(startfn(i)!=false)){'+'if(speed!=0){$(tabs.join()).stop(null,true).fadeTo(speed,0.1,function(){$(tabs.join()).css("display","none");$(tabs.join()).eq(i).css("display","block");});'+'$(tabs.join()).eq(i).stop(null,true).fadeTo(speed,1,function(){backfn?backfn(i):";"});}else{'+'$(tabs.join()).css("display","none");'+'$(tabs.join()).eq(i).css("display","block");'+'backfn?backfn(i):";"}'+'}});');});},butShowTab2:function(buts,tabs,targe,startfn,backfn){function doEvent(i){if(!startfn||(startfn(i)!=false)){if(tabs.eq(i).hasClass('active')){return;}
tabs.stop(null,true);tabs.filter('.active').animate({'opacity':0},400);buts.removeClass('active').eq(i).addClass('active');tabs.eq(i).css({'opacity':0,'z-index':3}).animate({'opacity':1},450,function(){tabs.removeClass('active').css({'z-index':1});$(this).addClass('active').css({'z-index':2});backfn?backfn(i):"";});}}
var targetType='mouseover';if(targe&&targe=='click'){targetType='click';}
tabs.css({'z-index':1}).filter('.active').css({'z-index':2});buts.each(function(i){if(targetType=='click'){$(this).click(function(){doEvent(i);});}else{$(this).mouseover(function(){doEvent(i);});}});},closeLightBox:function(options){alertdiv=$('.alertdiv,.layoverdiv').fadeOut();},hideLightBox:function(options){alertdiv=$('.alertdiv,.layoverdiv').css('display','none');}};jQuery.fn.setLightBox=function(options){if($.browser.msie&&$.browser.version=='6.0'){$('select').each(function(){if($(this).hasClass('none')||$(this).css('display')=='none')return;$(this).addClass('forieSelect none');});}
var layoverBg=options.layoverBg?options.layoverBg:'#fff';var layoverOpa=options.layoverOpa?options.layoverOpa:'0.5';var alertdivWidth=options.alertdivWidth?options.alertdivWidth:'auto';var alertdivHeight=options.alertdivHeight?options.alertdivHeight:'auto';var alertdivBg=options.alertdivBg?options.alertdivBg:'#fff';var closebut=options.closeBut;var layerdiv,alertdiv;var isfirst=true;if(jQuery('.layoverdiv').length==0){layerdiv=jQuery('<div class="layoverdiv" style="position:absolute;width:100%;height:100%;z-index:9998;left:0;top:0;display:none;"></div>');alertdiv=jQuery('<div class="alertdiv" style="position:absolute;top:50%;left:50%;display:none;z-index:9999;"></div>');jQuery('body').append(alertdiv).append(layerdiv);}else{isfirst=false;layerdiv=jQuery('.layoverdiv');if(options.multil){off=jQuery('.alertdiv').length*3+50+'%';alertdiv=jQuery('<div class="alertdiv alertmultil" style="position:absolute;top:'+off+';left:'+off+';display:none;z-index:9999;"></div>');jQuery('body').append(alertdiv);}else{jQuery('.alertmultil').remove();alertdiv=jQuery('.alertdiv');}}
layerdiv.css('background',layoverBg);layerdiv.height(jQuery('body').outerHeight(true)>document.documentElement.scrollHeight?jQuery('body').outerHeight(true):document.documentElement.scrollHeight);alertdiv.css({'width':alertdivWidth,'height':alertdivHeight}).html('').append(jQuery(this));if(!options.multil){layerdiv.css('opacity','0').css('display','block').fadeTo(500,layoverOpa);}
alertdiv.fadeIn(600,function(){layerdiv.height(jQuery('body').outerHeight(true)>document.documentElement.scrollHeight?jQuery('body').outerHeight(true):document.documentElement.scrollHeight);});if(!options.canNotDrag){var dragbodys=options.dragbody?alertdiv.find(options.dragbody):alertdiv;if(alertdiv.find('img').length!=0){if(options.closeBut||options.multil){dragbodys.drag({dragbody:alertdiv,opacity:'0.8',preventEvent:true});}else{dragbodys.drag({dragbody:alertdiv,opacity:'0.8',preventEvent:true,mouseupFn:function(){if(!draged){$.ml.closeLightBox();}}});}}else{if(options.closeBut||options.multil){dragbodys.drag({dragbody:alertdiv,opacity:'0.8'});}else{dragbodys.drag({dragbody:alertdiv,opacity:'0.8',mouseupFn:function(){if(!draged){$.ml.closeLightBox();}}});}}}
var mtop=-(alertdiv.outerHeight()/2);var clientH=document.documentElement.clientHeight;var clientW=document.documentElement.clientWidth;var stop=clientH/2+(document.documentElement.scrollTop==0?document.body.scrollTop:document.documentElement.scrollTop);if(stop+mtop<0){stop=20;mtop=0;}
var inwindow_padding=15;alertdiv.css('top',stop+'px');alertdiv.css({'margin-left':'-'+(alertdiv.outerWidth()/2+'px'),'margin-top':mtop+'px'});jQuery(this).add(jQuery(this).find('img')).load(function(){if(options.inWindow){if(($(this).height())>clientH){$(this).height(clientH-inwindow_padding*2);}
if((false&&$(this).width())>clientH){$(this).width(clientW-inwindow_padding*2);}}
stop=clientH/2+(document.documentElement.scrollTop==0?document.body.scrollTop:document.documentElement.scrollTop);mtop=-(alertdiv.outerHeight()/2);if(stop+mtop<0){stop=20;mtop=0;alertdiv.css('top',stop+'px');}
alertdiv.css('top',stop+'px');alertdiv.css({'margin-left':'-'+(alertdiv.outerWidth()/2+'px'),'margin-top':mtop+'px'});});if(!options.layerdivClick&&!options.multil){layerdiv.unbind('click').click(function(){$.ml.closeLightBox();});}
if(closebut!=undefined){alertdiv.find(closebut).unbind('click').click(function(){if(typeof(options.closeFn)=='function'&&options.closeFn()===false){return;}
if(options.closeSelf){$.ml.hideLightBox();}else if(options.multil){alertdiv.remove();}else{$.ml.closeLightBox();}});}
if(options.sureBut!=undefined){alertdiv.find(options.sureBut).unbind('click').click(function(){$(this).attr('disabled',true);if(options.closeSelf){$.ml.hideLightBox();}
if(typeof(options.sureFn)=='function'&&options.sureFn($(this),options.suerPara)===false){$(this).attr('disabled',false);return;}
$(this).attr('disabled',false);if(!options.closeSelf){if(options.multil){alertdiv.remove();}else{$.ml.closeLightBox();}}});}
if(options.closeSelfBut!=undefined){alertdiv.find(options.closeSelfBut).unbind('click').click(function(){alertdiv.remove();});}};})(jQuery);String.prototype.replaceAll=stringReplaceAll;function stringReplaceAll(AFindText,ARepText){raRegExp=new RegExp(AFindText,"g");return this.replace(raRegExp,ARepText)}
function modifURL(url){url=url.replace(/\%/g,'%25');url=url.replace(/\+/g,'%2B');url=url.replace(/ /g,'%20');url=url.replace(/\//g,'%2F');url=url.replace(/\?/g,'%3F');url=url.replace(/#/g,'%23');url=url.replace(/&/g,'%26');url=url.replace(/=/g,'%3D');return url;}
function str2html(str){str=str.replaceAll(' ','&nbsp;');str=str.replaceAll('>','&gt;');str=str.replaceAll('<','&lt;');str=str.replaceAll('"','&quot;');str=str.replaceAll('\'','&#39;');str=str.replaceAll('\n','<br/>');return str;}
function cutText(str,len,append){var a=0;var i=0;var temp='';for(i=0;i<str.length;i++){if(str.charCodeAt(i)>255)a+=2;else a++;if(a>len)return temp+(append?append:'');temp+=str.charAt(i);}
return str;}
function getByteCounts(str){var a=0;for(i=0;i<str.length;i++){if(str.charCodeAt(i)>255)a+=2;else a++;}
return a;}
function setCookie(name,value,ms){var exp=new Date();exp.setTime(exp.getTime()+ms);time=exp.toGMTString();document.cookie=name+"="+value+";expires="+time+";path=/";}
function getCookie(name)
{var mycookie=unescape(document.cookie);var cindex=mycookie.indexOf(name+"=");if(cindex!=-1)
{var cstart=cindex+name.length+1;var cend=mycookie.indexOf(";",cstart);if(cend==-1)
{cend=mycookie.length;}
return mycookie.substring(cstart,cend);}
return'';}
function orderByTable(header,body,p,backfn,valuefn){var h=$('body').append('<div id="orderHiddenDiv"></div>');$(header).click(function(){var index=$(this).prevAll().length;var temp=new Array(),bodyObject=$(body);var bodyLen=bodyObject.length;if(bodyLen==0)return;for(var i=0;i<bodyLen;i++){temp[temp.length]=i;}
var isAsc=false;if($(this).hasClass('asc')){$(header).removeClass('asc desc');$(this).addClass('desc');isAsc=true;}else{$(header).removeClass('asc desc');$(this).addClass('asc');isAsc=false;}
var temp_x='',temp_y='';var isnumber=$(this).attr('isnumber')=='1';temp.sort(function(x,y){if(!isAsc){if(typeof(valuefn)=='function'){temp_x=valuefn(bodyObject.eq(x).find('>').eq(index));temp_y=valuefn(bodyObject.eq(y).find('>').eq(index));}else{temp_x=bodyObject.eq(x).find('>').eq(index).text();temp_y=bodyObject.eq(y).find('>').eq(index).text();}}else{if(typeof(valuefn)=='function'){temp_y=valuefn(bodyObject.eq(x).find('>').eq(index));temp_x=valuefn(bodyObject.eq(y).find('>').eq(index));}else{temp_y=bodyObject.eq(x).find('>').eq(index).text();temp_x=bodyObject.eq(y).find('>').eq(index).text();}}
if(isnumber){temp_x=parseInt(temp_x);temp_x=typeof(temp_x)=='undefined'?0:temp_x;temp_y=parseInt(temp_y);temp_y=typeof(temp_y)=='undefined'?0:temp_y;}
return temp_x>temp_y?1:(temp_x<temp_y?-1:0);});var temp_object=new Array();for(var i=0;i<bodyLen;i++){$('#orderHiddenDiv').append(bodyObject.eq(temp[i]));}
$(p).append($('#orderHiddenDiv > '));if(typeof(backfn)=='function'){backfn();}});}
function isChecked(c){var ischecked=false;;$(c).each(function(){if($(this).attr('checked')){ischecked=$(this).attr('value');return false;};});return ischecked;;}/*  |xGv00|45300f620e0897a2356904406dac435c */